---
title: "Community Notes Data Codebook"
---

# Working with the Community Notes data

<https://communitynotes.x.com/guide/en/under-the-hood/download-data>

# Data snapshots

The [Community Notes data](https://x.com/i/communitynotes/download-data) is released as four separate files:

-   Notes: Contains a table representing all notes
-   Ratings: Contains a table representing all ratings
-   Note Status History: Contains a table with metadata about notes including what statuses they received and when.
-   User Enrollment: Contains a table with metadata about each user's enrollment state.

These tables can be joined on the `noteId` field to create a combined dataset with information about users, notes, and their ratings. The data is released in separate tables/files to reduce the dataset size by avoiding data duplication (this is known as a normalized data model).

A new snapshot of the Community Notes public data is released daily, on a best-effort basis, and technical difficulties may occur and delay the data release until the next day. We are not able to provide guarantees about when this may happen. The snapshots are cumulative files, but only contain notes and ratings that were created as of 48 hours before the dataset release time. When notes and ratings are deleted, they will no longer be released in any future versions of the data downloads, although the note status history dataset will continue to contain metadata about all scored notes even after they’ve been deleted, which includes noteId, creation time, the hashed participant ID of the note’s author, and a history of which statuses each notes received and when; however, all the content of the note itself e.g. the note’s text will no longer be available.

The data download page in Community Notes displays a date stamp indicating the most recent date of data included in the downloadable files.

# File structure

Each data snapshot table is stored in tsv (tab-separated values) file format with a header row. - The note and note rating data is directly taken from the user-submitted note creation and note rating forms, with minimal added metadata (like `ids` and `timestamp`). - The note status history file contains metadata derived from the raw notes and ratings, and contains the outputs of the note scoring algorithm. Below, we will describe each column’s data, including the question or source that generated the data, data type, and other relevant information.

| Field | Type | Description | Response values |
|------------------|------------------|------------------|------------------|
| noteId | Long | The unique ID of this note |  |
| participantId | String | A Community Notes-specific user identifier of the user who authored the note. This is a permanent id, which remains stable even if the user changes their username/handle. |  |
| createdAtMillis | Long | Time the note was created, in milliseconds since epoch (UTC). |  |
| tweetId | Long | The tweetId number for the tweet that the note is about. |  |
| classification | String | User-entered multiple choice response to note writing question: “Given current evidence, I believe this tweet is:” | "NOT\*MISLEADING", "MISINFORMEDORPOTENTIALLY_MISLEADING" |
| ~~believable~~ | String | User-entered multiple choice response to note writing question: “If this tweet were widely spread, its message would likely be believed by:” - Deprecated as of 2022-10-27. | "BELIEVABLEBYFEW", "BELIEVABLE_BY_MANY" |
| ~~harmful~~ | String | User-entered multiple choice response to note writing question: “If many believed this tweet, it might cause:” - Deprecated as of 2022-10-27. | "LITTLE*HARM", "CONSIDERABLE*HARM" |
| ~~validationDifficulty~~ | String | User-entered multiple choice response to note writing question: “Finding and understanding the correct information would be:” - Deprecated as of 2022-10-27. | "EASY", "CHALLENGING" |
| misleadingOther | Int | User-entered checkbox in response to question “Why do you believe this tweet may be misleading?” (Check all that apply question type). | 1 if “Other” is selected, else 0. |
| misleadingFactualError | Int | User-entered checkbox in response to question “Why do you believe this tweet may be misleading?” (Check all that apply question type). | 1 if “It contains a factual error” selected, else 0. |
| misleadingManipulatedMedia | Int | User-entered checkbox in response to question “Why do you believe this tweet may be misleading?” (Check all that apply question type). | 1 if “It contains a digitally altered photo or video” selected, else 0. |
| misleadingOutdatedInformation | Int | User-entered checkbox in response to question “Why do you believe this tweet may be misleading?” (Check all that apply question type). | 1 if “It contains outdated information that may be misleading” is selected, else 0. |
| misleadingMissingImportantContext | Int | User-entered checkbox in response to question “Why do you believe this tweet may be misleading?” (Check all that apply question type). | 1 if “It is a misrepresentation or missing important context” is selected, else 0. |
| misleadingUnverifiedClaimAsFact | Int | User-entered checkbox in response to question “Why do you believe this tweet may be misleading?” (Check all that apply question type). | 1 if “It presents an unverified claim as a fact” is selected, else 0. |
| misleadingSatire | Int | User-entered checkbox in response to question “Why do you believe this tweet may be misleading?” (Check all that apply question type). | 1 if “It is a joke or satire that might be misinterpreted as a fact” is selected, else 0. |
| notMisleadingOther | Int | User-entered checkbox in response to question “Why do you believe this tweet is not misleading?” (Check all that apply question type). | 1 if “Other” is selected, else 0. |
| notMisleadingFactuallyCorrect | Int | User-entered checkbox in response to question “Why do you believe this tweet is not misleading?” (Check all that apply question type). | 1 if “It expresses a factually correct claim” is selected, else 0. |
| notMisleadingOutdatedButNotWhenWritten | Int | User-entered checkbox in response to question “Why do you believe this tweet is not misleading?” (Check all that apply question type). | 1 if “This Tweet was correct when written, but is out of date now” is selected, else 0. |
| notMisleadingClearlySatire | Int | User-entered checkbox in response to question “Why do you believe this tweet is not misleading?” (Check all that apply question type). | 1 if “It is clearly satirical/joking” is selected, else 0. |
| notMisleadingPersonalOpinion | Int | User-entered checkbox in response to question “Why do you believe this tweet is not misleading?” (Check all that apply question type). | 1 if “It expresses a personal opinion” is selected, else 0. |
| trustworthySources | Int | Binary indicator, based on user-entered multiple choice in response to note writing question “Did you link to sources you believe most people would consider trustworthy?” | 1 if “Yes” is selected, 0 if “No” is selected |
| summary | String | User-entered text, in response to the note writing prompt “Please explain the evidence behind your choices, to help others who see this tweet understand why it is not misleading” | User entered text explanation, with some characters escaped (e.g. tabs converted to spaces). |
| isMediaNote | Int | User-entered checkbox in response to question “Is your note about the Tweet or the image?”. New as of 2023-05-24. | 1 if “About the image in this Tweet, and should appear on all Tweets that include this image” is selected, and 0 otherwise (including if "About this specific Tweet" is selected). |
